apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: md5u81on4-dotnet-basic
  janus-idp.io/tekton: md5u81on4-dotnet-basic
  backstage.io/kubernetes-id: md5u81on4-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: md5u81on4-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
